### ISSUE TITLE
[Bug][Creator] When one API name is a substring of another - second one will not be generated

### ISSUE THREAD

**Issue by MichalKosowski** [Azure/azure-api-management-devops-resource-kit#213]
I have following apis defined:

    apis:
      - name: Client
        serviceUrl: 'https://someservice.com'
        # other setup
      - name: ClientService
        serviceUrl: 'https://other.com
        #remaining setup

**Expected Outcome:**
- generated arm templates for both Client and ClientService apis

**Actual outcome:**
- only Client template is generated

**Reason:**
In file Create.cs on line 105 following code is executed:

`APIConfig providedAPIConfiguration = creatorConfig.apis.FirstOrDefault(api => apiResource.name.Contains(api.name));`

Which uses the string Contains() method. Becouse of that, second api (ClientService) is matched with configuration for first one (as it contains "Client" in its name).

**Solution:**
Raplace that line with following:
`APIConfig providedAPIConfiguration = creatorConfig.apis.FirstOrDefault(api => apiResource.properties.displayName.Equals(api.name));`
`

**Comment by dldldlepl** [comment]
For me the quick fix has broken the Creator tool as it now displays an error message:
```
...
Creating API templates
------------------------------------------
Object reference not set to an instance of an object.
```
This happend at the position of the quick fix for creating a subsequent template. For me this would better fix the problem: 
`
APIConfig providedAPIConfiguration = creatorConfig.apis.FirstOrDefault(api => apiResource.name.Equals($"[concat(parameters('ApimServiceName'), '/{api.name}')]", StringComparison.Ordinal));
`

**Comment by MichalKosowski** [comment]
Hi,

What is your yaml set up? (apis names?)

**Comment by dldldlepl** [comment]
I have for example this configuration, which produces this error:
```
version: 0.0.1
apimServiceName: api
apiVersionSets:
  - id: apiServiceVersionAlpha
    displayName: Api Version alpha
    description: Description for the Api
    versioningScheme: Segment
    versionQueryName: alpha
    versionHeaderName: alpha
apis:
  - name: Api
    type: http
    description: myFirstAPI
    serviceUrl: api.example.com
    openApiSpec: ../../Api_Alpha.json
    policy: ./CloudAPI/Version1/policy.xml
    suffix: alpha
    subscriptionRequired: true
    isCurrent: true
    apiVersion: alpha
    apiVersionDescription: alpha Version of the api
    apiVersionSetId: apiServiceVersionAlpha
    apiRevision: 1
    apiRevisionDescription: first api revision
    operations:
      add:
        policy: ./CloudAPI/Version1/Operations/add.policy.xml
      subtract:
        policy: ./CloudAPI/Version1/Operations/subtract.policy.xml
      configurationGet:
        policy: ./CloudAPI/Version1/Operations/configuration.policy.xml
    products: default
products:
  - displayName: default
    description: Default access product for all current users
    terms: 
    subscriptionRequired: true
    approvalRequired: true
    subscriptionsLimit: 1000000
    state: notPublished
    policy: ./Products/default.policy.xml
backends:
    - title: Api Backend
      description: Api Backend
      url: api.example.com
      protocol: https
      tls:
        validateCertificateChain: true
        validateCertificateName: true
outputLocation: ./Output
linked: false
```
