### ISSUE TITLE
How to publish new revision

### ISSUE THREAD

**Issue by joserendal** [Azure/azure-api-management-devops-resource-kit#218]
Hi All,

As part of an automatic CICD cycle in Azure, I was trying to publish a new revision of a deployed API with the creator.

First time I deploy it I'm using this config file for the creator:

```
version: 0.0.1
apimServiceName: testting
apiVersionSets:
    - id: apiAdministrativosVersionSetId-from-creator
      displayName: API Administrativos.
      versioningScheme: Query
      versionQueryName: versionQuery
      versionHeaderName: versionHeader
apis:
    - name: api-administrativos--echo
      # Api has to be in JSON format
      openApiSpec: ..\..\json-files\_Administrativos.json
      policy: ..\..\policies\global-policy-echo.xml
      suffix: administrativos
      subscriptionRequired: false
      apiVersion: echo
      apiVersionDescription: My first version
      apiVersionSetId: apiAdministrativosVersionSetId-from-creator
-    apiRevision: 1
+    apiRevision: 2
-    apiRevisionDescription: My first revision
+    apiRevisionDescription: My second revision
      products: starter, unlimited
outputLocation: ..\..\creatorGeneratedTemplates
```

And it's published correctly on Azure.
Then, I'm making a change in the API definition and changing the config file the way I'm showing.

I was expecting Azure to create a new revision, but instead it's just updating revisión 1 with the swagger contents and the description provided, but not creating a new revision.

What am I doing wrong?

Regards,
Jose
