### ISSUE TITLE
[Creator] when deploying different api version (same api version set) an exception is thrown

### ISSUE THREAD

**Issue by jezyj-ix** [Azure/azure-api-management-devops-resource-kit#361]
We have two versions of our api V1 and V2. We have used Creator tool to generate templates for V1 and separately for V2.

When deploying V2 project we get the following error: `Cannot create API with the same Path 'apipath' as API unless it's a part of the same version set`.

This is a sample config for v1 and v2:

### V1
```
version: 0.0.1
apimServiceName: ourApim
outputLocation: ./templates
apiVersionSets:
    - id: apiVersions
      displayName: apiVersions
      description: api versions
      versioningScheme: Segment 
apis:
    - name: ourapi
      apiVersion: V1
      apiVersionDescription: API version 1
      apiVersionSetId: apiv1
      serviceUrl: ...
      description: Our api v1
      openApiSpec: ...
      suffix: apipath
      isCurrent: true
```

### V2
```
version: 0.0.1
apimServiceName: ourApim
outputLocation: ./templates
apiVersionSets:
    - id: apiVersions
      displayName: apiVersions
      description: api versions
      versioningScheme: Segment 
apis:
    - name: ourapi
      apiVersion: V2
      apiVersionDescription: API version 2
      apiVersionSetId: apiv2
      serviceUrl: ...
      description: Our api v2
      openApiSpec: ...
      suffix: apipath
      isCurrent: true
```
