### ISSUE TITLE
Extractor doesn't extract a template for a custom User Group

### ISSUE THREAD

**Issue by AjaySewradj** [Azure/azure-api-management-devops-resource-kit#445]
Bug: The Extractor doesn't extract a template for a custom User Group, but does mention a reference to it in the 'Products' template. Deployment of the 'Products' ARM template fails because the User Group doesn't exist in the target APIM instance.

Steps to reproduce:
- Create a custom User Group in an APIM instance. The list of UserGroups would be Administrators, Developers, Guests, MyCustomGroup.

- Select a Product and use 'Access Control' to assign access to all UserGroups (including MyCustomGroup)

- Use the Extractor tool to extract templates
- Note that the Product template contains a reference to MyCustomGroup, but there is no template for actually creating the MyCustomGroup

Manual Fix:
I've added the following ARM template to my build pipeline to create MyCustomGroup, it would be helpful if the Extractor tool could generate it
```yml
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "ApimServiceName": {
            "type": "string"
        }
    },
    "resources": [
        {
            "type": "Microsoft.ApiManagement/service/groups",
            "name": "[concat(parameters('ApimServiceName'), '/MyCustomGroup')]",
            "apiVersion": "2019-01-01",
            "properties": {
                "displayName": "MyCustomGroup",
                "description": "Custom user group",
                "type": "custom",
                "externalId": null
            },
            "resources": []
        }
    ]
}
```
