### ISSUE TITLE
Creator fails when an API has not associated products

### ISSUE THREAD

**Issue by springcomp** [Azure/azure-api-management-devops-resource-kit#499]
## Steps to reproduce

Here is the extract of a YAML configuration file:

```
apis:
    - description: Echo API
      isCurrent: true
      name: echo-api
      openApiSpec: ./echo-api-swagger.json
      serviceUrl: https://webap-clicup-we1-int.azurewebsites.net
      subscriptionRequired: true
      suffix: /echo
```

The failure happens because there is no check for this situation in [ProductAPITemplateCreator.cs](https://github.com/Azure/azure-api-management-devops-resource-kit/blob/af4a5e2af604cc047b9e56baeed6b6e2ebdd7dcd/src/APIM_ARMTemplate/apimtemplate/Creator/TemplateCreators/ProductAPITemplateCreator.cs#L23)
