### ISSUE TITLE
[Creator] How to parameterized secure NameValues or use keyvault?

### ISSUE THREAD

**Issue by majorvin** [Azure/azure-api-management-devops-resource-kit#557]

**Comment by springcomp** [comment]
@majorvin The `Creator` tool natively supports creating named values that are references to a key vault secret.

You must first enable _managed identity_ on your Azure API Management instance and set a corresponding access policy on the Key Vault resource hosting the secrets.

Then you can use the following syntax to reference a key vault secret:

```yaml
version: 0.0.1
apimServiceName: apim-lplcloud-dev
apiVersionSets:
apis:
- description: int-httpbin-org
  name: httpin-org
  openApiSpec: ./httpbin.org.swagger.json
  openApiSpecFormat: OpenApi30_Json
  serviceUrl: https://httpbin.org
  subscriptionRequired: false
  suffix: /int/httpbin-org

namedValues:
- displayName: named-value
  secret: true
  keyVault:
    secretIdentifier: https://vault-name.vault.azure.net/secrets/secret-name

```
