### ISSUE TITLE
Bug: Issue when extracting and deploying the swagger definition files.

### ISSUE THREAD

**Issue by ratheeshps** [Azure/azure-api-management-devops-resource-kit#821]
### Report

I have generated ARM templates using extractor tool. In the config, i have mentiond the OpenAPISpec as swagger definition (json).
``` yaml
openApiSpec: ./design-api.json   # Required, can be url or local file
openApiSpecFormat: swagger
```

I deployed it into an APIM, it worked fine.

Now extracted the same API using below command
``` bash
apim-templates extract --sourceApimName apim-dev-001 --destinationApimName apim-test-002 --resourceGroup rg-dev-001 --apiName DesignApi --fileFolder ./templates
```

Then deployed the ApiVersionSets, Tags and API templates in the order.
I can see APIs and all gets deployed. But the pipeline keeps on running for 1 hour and 2 hours.

### Expected Behavior

Deployment should complete

### Actual Behavior

Deployment runs continuously even after deploying.

### Steps to Reproduce the Problem

1.I have generated ARM templates using extractor tool. In the config, i have mentioned the OpenAPISpec as swagger definition (json).
```
openApiSpec: ./design-api.json   # Required, can be url or local file
openApiSpecFormat: swagger
```

2. I deployed it into an APIM, it worked fine.

3. Now extracted the same API using below command
```
apim-templates extract --sourceApimName apim-dev-001 --destinationApimName apim-test-002 --resourceGroup rg-dev-001 --apiName DesignApi --fileFolder ./templates
```

4. Then deployed the ApiVersionSets, Tags and API templates in the order.
5. I can see APIs and all gets deployed. But the pipeline keeps on running for 1 hour and 2 hours.

### Component

Extractor

### DevOps Resource Kit Version

1.0.0

### .NET Version

6.0

### OS

Windows. No WSL

### Configuration

Configuration:

```
version: 0.0.1   # Required
apimServiceName: apim-dev-001 # Required, must match name of an apim service deployed in the specified resource group
apiVersionSets:   # Optional
  - id: design-versionset-id-01
    displayName: design-API
    description: a description
    versioningScheme: Query
    versionQueryName: versionQuery
    versionHeaderName: versionHeader
apis:
  - name: DesignApi   # Required
    openApiSpec: ./design-api.json   # Required, can be url or local file
    openApiSpecFormat: swagger
    serviceUrl: http://myApiBackendUrl.com
    policy: ./policies/apiPolicyHeaders.xml   # Optional, can be url or local file
    suffix: design-api   # Required
    apiVersion: v1   # Optional
    apiVersionDescription: My first version   # Optional
    apiVersionSetId: design-versionset-id-01
    revision: 1   # Optional
    revisionDescription: My first revision   # Optional
    operations:   # Optional
      get-health: # Must match the operationId property of a path's operations
        policy: ./policies/operationRateLimit.xml   # Optional, can be url or local file
    authenticationSettings:   # Optional
      subscriptionKeyRequired: false
outputLocation: ../templates    # Required, folder the creator will write the templates to
```

### API Management Configuration

Developer Version
Yes
No VNET

### Logs

```shell
example
```
